#include <iostream>
#include <string>
#include <vector>
using namespace std;
/*
 * [389] Find the Difference
 *
 * https://leetcode.com/problems/find-the-difference/description/
 *
 * algorithms
 * Easy (51.54%)
 * Total Accepted:    109.4K
 * Total Submissions: 212.2K
 * Testcase Example:  '"abcd"\n"abcde"'
 *
 *
 * Given two strings s and t which consist of only lowercase letters.
 *
 * String t is generated by random shuffling string s and then add one more
 * letter at a random position.
 *
 * Find the letter that was added in t.
 *
 * Example:
 *
 * Input:
 * s = "abcd"
 * t = "abcde"
 *
 * Output:
 * e
 *
 * Explanation:
 * 'e' is the letter that was added.
 *
 */
class Solution {
public:
  char findTheDifference(const string &s, const string &t) {
    char x = 0;
    for (char ch : s) {
      x ^= ch;
    }
    for (char ch : t) {
      x ^= ch;
    }
    return x;
  }

  char findTheDifference2(const string &s, const string &t) {
    vector<bool> v(26, false);

    for (char ch : s) {
      int c = ch - 'a';
      v[c] = !v[c];
    }

    for (char ch : t) {
      int c = ch - 'a';
      v[c] = !v[c];
    }

    for (int i = 0; i < 26; ++i) {
      if (v[i]) {
        return 'a' + i;
      }
    }
  }
};

#ifdef DEBUG
int main() {
  Solution sol;
  cout << sol.findTheDifference("abcd", "abcde") << endl;
}
#endif
